export const PostConstants = {
    POST_ADD_REQUEST: 'POST_ADD_REQUEST',
    POST_ADD_SUCCESS: 'POST_ADD_SUCCESS',
    POST_ADD_FAIL: 'POST_ADD_FAIL',

    GET_ALL_POST_REQUEST: 'GET_ALL_POST_REQUEST',
    GET_ALL_POST_SUCCESS: 'GET_ALL_POST_SUCCESS',
    GET_ALL_POST_FAIL: 'GET_ALL_POST_FAIL',

    GET_POST_DETAIL_REQUEST: 'GET_POST_DETAIL_REQUEST',
    GET_POST_DETAIL_SUCCESS: 'GET_POST_DETAIL_SUCCESS',
    GET_POST_DETAIL_FAIL: 'GET_POST_DETAIL_FAIL',

    UPLOAD_AVATAR_AND_IMAGE_REQUEST: 'UPLOAD_AVATAR_AND_IMAGE_REQUEST',
}