export const FeeConstants = {
    CREATE_FEE_REQUEST: 'CREATE_FEE_REQUEST',
    CREATE_FEE_SUCCESS: 'CREATE_FEE_SUCCESS',
    CREATE_FEE_FAIL: 'CREATE_FEE_FAIL',

    GET_ALL_FEES_REQUEST: 'GET_ALL_FEES_REQUEST',
    GET_ALL_FEES_SUCCESS: 'GET_ALL_FEES_SUCCESS',
    GET_ALL_FEES_FAIL: 'GET_ALL_FEES_FAIL',
}